applications:
  - name: vanquish-bpm-framework
    memory: 1G
    instances: 1
    random-route: false
camunda.bpm:
  admin-user:
    id: admin
    password: admin
    firstName: Lithesh
    history-level: full
    history-level-default: full
  filter:
    create: All tasks
  database:  
    schema-update: true
    type: h2

camunda.bpm.application:
   scan-for-process-definitions: true
   